# Generated by Django 5.2.8 on 2025-11-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="link",
            old_name="movie",
            new_name="movieId",
        ),
    ]
