# Generated by Django 5.2.8 on 2025-11-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0002_rename_movie_link_movieid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="timestamp",
            field=models.IntegerField(),
        ),
    ]
