# Generated by Django 5.2.8 on 2025-11-12 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0003_alter_tag_timestamp"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["genres"], name="movie_movie_genres_c23707_idx"),
        ),
        migrations.AddIndex(
            model_name="movie",
            index=models.Index(fields=["title"], name="movie_movie_title_0a2a49_idx"),
        ),
    ]
