# Generated by Django 5.2.8 on 2025-11-12 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0004_movie_movie_movie_genres_c23707_idx_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="movie",
            name="movie_movie_genres_c23707_idx",
        ),
    ]
