# Generated by Django 5.2.8 on 2025-11-12 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("movie", "0005_remove_movie_movie_movie_genres_c23707_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="movie",
            name="movieId",
            field=models.IntegerField(unique=True),
        ),
    ]
